feat: Add new ways to fetch git date
eiriksm/php-app-git-version pull request #32
Opened 2022-09-28 07:54 UTC by esolitos

TBD: Draft

2022-10-13 17:40 UTC, eiriksm requested changes

2022-10-13 17:40 UTC, eiriksm commented on src/GitInfo.php
> +   * Fetches the date from
Seems like an incomplete comment?

2022-10-17 09:00 UTC, esolitos commented on src/GitInfo.php
> +   * Fetches the date from
Good point. 😅  Fixed it.

2022-10-18 04:54 UTC, eiriksm approved these changes

2022-10-18 04:57 UTC, eiriksm requested changes
Tests are also failing. plus, would prefer to have test coverage for all new things please 🤓

2022-10-18 06:32 UTC, esolitos commented
I fixed the existing tests and added to simple tests, not sure if we should check the format perhaps?

2022-10-26 02:22 UTC, merged

2022-10-26 02:22 UTC, eiriksm commented
Fixed something that seemed like copy paste, and merged. Thanks!